
---
- hosts: all
become: yes
tasks:
- name: Créer les utilisateurs
user:
name: '{{ cherif1 , cherif2 , cherif3 }}'
state: present
groups: admin
shell: /bin/bash
with_items:
- cherif1
- cherif2
- cherif3
- name: Créer des clés ssh
authorized_key:
user: '{{ item.name }}'
key: '{{ item.key }}'
with_items:
- { name: cherif1, key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCuNQHkLenG6fos4cG2Qcl9FlNmTuucwXaoHfmgttnceYkGyYsoRRJzvx+VIoRESZB1/LbDPy87ab+rIVSrSvUxLpWtKsPPoknLfCGKM1QfsMbhg2Bh3VMMofLU5N8um0u38vLKtBELeu7TWg0KEP5sJcNeWkemAXJDVFJFkD0hwJsKD5Nq88L+dLlKaLMxWDrLFWquZ+VBc6yO0ZCd+Se3jWts+DY8pHZKeL/VMhz5EC9uFwzmsUZHxVllonv1x6gWh5osJZQdbN18FN1jhOe96M0FT90bIgfNUwTSjRb9DGyuxhyzbLK6Z+lMD72+0nz7KXMeJXZnfKeI6PzCr8LP5oaNc2G/soSSnMON9jXqKhE734bedMEBrglwO6NYrsZSn+VRTZe3dMir9c1M80PCIhahC++GDJ7WSlx6gXROp/AydvGjq1Y1z0mQihvhOzgHcrFHcPWo4OJJzVU+I0vbOQgzfc4axVnvXSy45Xpk0lMfsR7OvY853kdnXSxfgIc= cherif@ADMINSYS' }
- { name: cherif2, key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQC41DEfnmjjFNQEH4gMLoV2xD/PRHc9BOvz2Zm+VHbGTsWRBrn0KFf8eXABM1/m/N2XnpvTrlV/BRHfXhiKFfjLI2fLoRjiBL5Vh2KwhpskWZ7DSRdYllcf1YIG7SbdlUcRuN4Pg/FxQ/+5mS/+riXbZoCAvoJHa1bIiguHTSS7kbl3hsh+HJSBU5pk6ikZ+p+IvesJeCPLCJm7wiCX7G8tziSB2w9KGmjYujnCBMEHCsClir70eujZRrn1G6BmQrHoC/6G3aoolI17VjuqC9P9QCiWKuzEdN9+1FUNIq0eohuhgf5TLqVJxmeET85gq4ZFaw7pbvqsykdOlL+eSIsM4H/t3kZ6NfzS9sRz0SK5JRbFyf3ewPDi6S8APRroOwd4nzrm+uxSI/t3zU6Wj2093Yqqj5XcKalPrgiQ6F0YSk4q8wER9Lcx0ll5uDLxf8Y5DHhIs92V4V+uXz2sHo3je3BmYOfkEZLDN9Y2URSVbaLxqVjuHC631vOM6t8KS5k= cherif@ADMINSYS' }
- { name: cherif3, key: 'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDQxm5XJK9EXJB/fEoebpYacZQr3y9pzKGO4QFa9F3XhhX3BmAPkJmSMK3gbNYZ3RYC+snCyUfu4/4EvHR63j5D23dPUllBWAZrfR+bO9+uDaP/QfFG4umbApEgnI8bBh5eMM/arTctN2XLvr2IqhkvjEgzxRM7KU2o75aR8MLUsydPV0CNB/I8gN8mowYOMDdtzN4Of7Eb4QyTJ8Cvaq2ivmEMImgn4rih5sDNUvRYmMIwd8iSMozi8DLKaxu4MNgHLVqLArrDPMXlVf5QbQ6uhCWQDeT7/hbn7Z8EjuoQ2l7RTPaGoZ/1zsdhxJJhr3mbZxin4Tsr5ZSZF1AEa8DSvM0zUGOXMTtXE1Vm6qzjI0CKg2GMo+XpJNdCEXxH+Xz5YPv9V+baDUYuIwqpOxmNYoVNjTvkp27yHPPXQWmeGRqHqZHb4D/kTOF9Og5qDkpP+bL4owqRWPlxFx2DTbWsPVfQfYDPxFcZvZrpt6UXh8BKAP0m/WVH3QEPDq9I57M= cherif@ADMINSYS' }